<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jurusan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('user_model');
        $this->load->model('Jurusan_model');
    } 

    /*
     * Listing of jurusan
     */
    function index()
    {
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        $data['jurusan'] = $this->Jurusan_model->get_all_jurusan();
        
        $this->load->view('templates/header',$data);
        $this->load->view('jurusan/index', $data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new jurusan
     */
    function add()
    {   
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'nama_jurusan' => $this->input->post('nama_jurusan'),
            );
            
            $jurusan_id = $this->Jurusan_model->add_jurusan($params);
            redirect('jurusan/index');
        }
        else
        {            
            $this->load->view('templates/header',$data);
            $this->load->view('jurusan/add');
            $this->load->view('templates/footer');
        }
    }  

    /*
     * Editing a jurusan
     */
    function edit($id_jurusan)
    {   
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);
        // check if the jurusan exists before trying to edit it
        $data['jurusan'] = $this->Jurusan_model->get_jurusan($id_jurusan);
        
        if(isset($data['jurusan']['id_jurusan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'nama_jurusan' => $this->input->post('nama_jurusan'),
                );

                $this->Jurusan_model->update_jurusan($id_jurusan,$params);            
                redirect('jurusan/index');
            }
            else
            {
                $this->load->view('templates/header',$data);
                $this->load->view('jurusan/edit', $data);
                $this->load->view('templates/footer');
            }
        }
        else
            show_error('The jurusan you are trying to edit does not exist.');
    } 

    /*
     * Deleting jurusan
     */
    function remove($id_jurusan)
    {
        $jurusan = $this->Jurusan_model->get_jurusan($id_jurusan);

        // check if the jurusan exists before trying to delete it
        if(isset($jurusan['id_jurusan']))
        {
            $this->Jurusan_model->delete_jurusan($id_jurusan);
            redirect('jurusan/index');
        }
        else
            show_error('The jurusan you are trying to delete does not exist.');
    }
    
}
