<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kegiatan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->library('form_validation');
        $this->load->helper('MY');
        $this->load->model('user_model');
        $this->load->model('Kegiatan_model');
        $this->load->model('kategori_model');
        $this->load->model('kategori_induk_model');
        $this->load->model('notifikasi_model');
    } 

    /*
     * Listing of kegiatan
     */
    function index()
    {
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $data['kegiatan'] = $this->Kegiatan_model->get_all_kegiatan();
        
        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);
    
        $this->load->view('templates/header', $data);
        $this->load->view('kegiatan/index', $data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new kegiatan
     */
    function add()
    {   
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        $data['kategori_induk'] = $this->kategori_induk_model->generate_kategori_induk_dropdown();
        $data['all_kategori_induk_wajib'] = $this->kategori_induk_model->get_all_kategori_induk_wajib();
        $data['all_kategori_induk_tidak_wajib'] = $this->kategori_induk_model->get_all_kategori_induk_tidak_wajib();
        $data['all_kategori_induk'] = $this->kategori_induk_model->get_all_kategori_induk();

        $data['kategori'] = $this->kategori_model->generate_kategori_dropdown();

        $this->load->helper('form');
        // Kita validasi input sederhana, sila cek http://localhost/ci3/user_guide/libraries/form_validation.html
        $this->form_validation->set_rules('nama_kegiatan', 'nama_kegiatan', 'required',
            array(
                'required'      => 'Isi %s terlebih dahulu.',
            ));
        // Cek apakah input valid atau tidak
        if ($this->form_validation->run() === FALSE)
        {
            $this->load->view('templates/header', $data);
            $this->load->view('Kegiatan/add', $data);
            $this->load->view('templates/footer');
        } else {
            // Apakah user upload gambar?
            if ( isset($_FILES['thumbnail']) && $_FILES['thumbnail']['size'] > 0 )
            {
                // Konfigurasi folder upload & file yang diijinkan
                // Jangan lupa buat folder uploads di dalam ci3-course
                $config['upload_path']          = './assets/img/kegiatan/';
                $config['allowed_types']        = 'gif|jpg|png';
                $config['max_size']             = 2048;
                // Load library upload
                $this->load->library('upload', $config);
                // Apakah file berhasil diupload?
                if ( ! $this->upload->do_upload('thumbnail'))
                {
                    $data['upload_error'] = $this->upload->display_errors();
                    $post_image = '';
                    // Kita passing pesan error upload ke view supaya user mencoba upload ulang
                    $this->load->view('templates/header', $data);
                    $this->load->view('Kegiatan/add', $data);
                    $this->load->view('templates/footer');
                } else {
                    // Simpan nama file-nya jika berhasil diupload
                    $img_data = $this->upload->data();
                    $post_image = $img_data['file_name'];
                    
                }
            } else {
                // User tidak upload gambar, jadi kita kosongkan field ini
                $post_image = '';
            }
            // Memformat slug sebagai alamat URL, 
            // Misal judul: "Hello World", kita format menjadi "hello-world"
            // Nantinya, URL blog kita menjadi mudah dibaca     
            // http://localhost/ci3-course/blog/hello-world
            $post_data = array(
                'nama_kegiatan' => $this->input->post('nama_kegiatan'),
                'fk_kategori_induk_kegiatan' => $this->input->post('kode_kategori_induk'),
                'fk_kategori_kegiatan' => $this->input->post('kode_kategori'),
                'dibuat' => $this->input->post('dibuat'),
                'tggl_kegiatan' => $this->input->post('tggl_kegiatan'),
                'kuota' => $this->input->post('kuota'),
                'gambar' => $post_image,
                'terbit' => $this->input->post('terbit'),
            );
            // Jika tidak ada error upload gambar, maka kita insert ke database via model Blog 
            if( empty($data['upload_error']) ) {
                $this->Kegiatan_model->add_kegiatan($post_data);
                    redirect('kegiatan');
            }
        }
    }  

    /*
     * Editing a kegiatan
     */
    function edit($id = NULL)
    {   
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        $data['kegiatan'] = $this->Kegiatan_model->get_kegiatan_by_id($id);
        // Jika id kosong atau tidak ada id yg dimaksud, lempar user ke halaman blog
        if ( empty($id) || !$data['kegiatan'] ) redirect('kegiatan');
        // Gunakan fungsi dari model untuk mengisi data dalam dropdown
        $data['kategori'] = $this->kategori_model->generate_kategori_dropdown();
        // Kita simpan dulu nama file yang lama
        $old_image = $data['kegiatan']->gambar;
        // Kita butuh helper dan library berikut
        $this->load->helper('form');
        // Kita validasi input sederhana, sila cek http://localhost/ci3/user_guide/libraries/form_validation.html
        $this->form_validation->set_rules('nama_kegiatan', 'nama_kegiatan', 'required',
            array(
                'required'      => 'Isi %s donk, males amat.'
            ));
        // Cek apakah input valid atau tidak
        if ($this->form_validation->run() === FALSE)
        {
            $this->load->view('templates/header',$data);
            $this->load->view('kegiatan/edit', $data);
            $this->load->view('templates/footer');
        } else {
            // Apakah user upload gambar?
            if ( isset($_FILES['thumbnail']) && $_FILES['thumbnail']['size'] > 0 )
            {
                // Konfigurasi folder upload & file yang diijinkan
                // Jangan lupa buat folder uploads di dalam ci3-course
                $config['upload_path']          = './assets/img/kegiatan/';
                $config['allowed_types']        = 'gif|jpg|png';
                $config['max_size']             = 2048;
                $config['max_width']            = 1000;
                $config['max_height']           = 2000;
                // Load library upload
                $this->load->library('upload', $config);
                // Apakah file berhasil diupload?
                if ( ! $this->upload->do_upload('thumbnail'))
                {
                    $data['upload_error'] = $this->upload->display_errors();
                    $post_image = '';
                    // Kita passing pesan error upload ke view supaya user mencoba upload ulang
                    $this->load->view('templates/header',$data);
                    $this->load->view('kegiatan/edit', $data);
                    $this->load->view('templates/footer');
                } else {
                    // Hapus file image yang lama jika ada
                    if( !empty($old_image) ) {
                        if ( file_exists( './assets/img/kegiatan/'.$old_image ) ){
                            unlink( './assets/img/kegiatan/'.$old_image );
                        } else {
                            echo 'File tidak ditemukan.';
                        }
                    }
                    // Simpan nama file-nya jika berhasil diupload
                    $img_data = $this->upload->data();
                    $post_image = $img_data['file_name'];
                    
                }
            } else {
                // User tidak upload gambar, jadi kita kosongkan field ini, atau jika sudah ada, gunakan image sebelumnya
                $post_image = ( !empty($old_image) ) ? $old_image : '';
            }
            // $slug = url_title($this->input->post('tipe'), 'dash', TRUE);
            $post_data = array(
                'nama_kegiatan' => $this->input->post('nama_kegiatan'),
                'fk_kategori_kegiatan' => $this->input->post('fk_kategori_kegiatan'),
                'tggl_kegiatan' => $this->input->post('tggl_kegiatan'),
                'kuota' => $this->input->post('kuota'),
                'gambar' => $post_image,
                'terbit' => $this->input->post('terbit'),
            );
            // Jika tidak ada error upload gambar, maka kita update datanya 
            if( empty($data['upload_error']) ) {
                // Update artikel sesuai post_data dan id-nya
                $this->Kegiatan_model->update_kegiatan($post_data, $id);
                redirect('kegiatan');
            }
        }
    } 

    /*
     * Deleting kegiatan
     */
    function remove($id_kegiatan)
    {
        // $kegiatan = $this->Kegiatan_model->get_kegiatan($id_kegiatan);

        // // Jika id kosong atau tidak ada id yg dimaksud, lempar user ke halaman blog

        // // check if the kegiatan exists before trying to delete it
        // if(isset($kegiatan['id_kegiatan']))
        // {
        //     $this->Kegiatan_model->delete_kegiatan($id_kegiatan);
        //     redirect('kegiatan/index');
        // }
        // else
        //     show_error('The kegiatan you are trying to delete does not exist.');
        $data['kegiatan'] = $this->Kegiatan_model->get_kegiatan($id_kegiatan);
        // Jika id kosong atau tidak ada id yg dimaksud, lempar user ke halaman blog
        if ( empty($id_kegiatan) || !$data['kegiatan'] ) show_404();
        // Kita simpan dulu nama file yang lama
        $old_image = $data['kegiatan']->gambar;
        // Hapus file image yang lama jika ada
        if( !empty($old_image) ) {
            if ( file_exists( './assets/img/kegiatan/'.$old_image )){
                unlink( './assets/img/kegiatan/'.$old_image);
            } else {
                echo 'File tidak ditemukan.';
            }
        }
        // Hapus artikel sesuai id-nya
        if( ! $this->Kegiatan_model->delete_kegiatan($id_kegiatan) )
        {
            // Jika gagal, tampilkan failnya
            echo "gagal menghapus";
        } else {
            // Ok, sudah terhapus
            redirect('kegiatan');
        }
    }
    
}
