<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kegiatan_pengguna extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('kegiatan_pengguna_model');
        $this->load->model('user_model');
        $this->load->model('notifikasi_model');
    } 

    /*
     * Listing of kegiatan_pengguna
     */
    function index()
    {
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $data['kegiatan_pengguna'] = $this->kegiatan_pengguna_model->get_all_kegiatan_pengguna();
        
        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);
    
        $this->load->view('templates/header', $data);
        $this->load->view('kegiatan_pengguna/index', $data);
        $this->load->view('templates/footer');
    }


    function daftar_keg_mah($id){
        $user = $this->kegiatan_pengguna_model->get_kegiatan_pengguna($id);
        $user_id=$user['fk_id_user'];

        $post_data = array('terdaftar' => 1,
            );
            $this->kegiatan_pengguna_model->update_keg_pengguna($post_data, $id);
                redirect('kegiatan_pengguna');
    }
    function btl_daftar_keg_mah($id){
        $user = $this->kegiatan_pengguna_model->get_kegiatan_pengguna($id);
        $user_id=$user['fk_id_user'];

        $post_data = array('terdaftar' => 0,
            );
            $this->kegiatan_pengguna_model->update_keg_pengguna($post_data, $id);
                redirect('kegiatan_pengguna');
    }

    /*
     * Deleting kegiatan_pengguna
     */
    function remove($id_daftar_keg)
    {
        $kegiatan_pengguna = $this->kegiatan_pengguna_model->get_kegiatan_pengguna($id_daftar_keg);

        // check if the kegiatan_pengguna exists before trying to delete it
        if(isset($kegiatan_pengguna['id_daftar_keg']))
        {
            $this->kegiatan_pengguna_model->delete_kegiatan_pengguna($id_daftar_keg);
            redirect('kegiatan_pengguna/index');
        }
        else
            show_error('The kegiatan_pengguna you are trying to delete does not exist.');
    }
    
}
