<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Level extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->library('form_validation');
        $this->load->helper('MY');
        $this->load->model('user_model');
        $this->load->model('Level_model');
        $this->load->model('notifikasi_model');
    } 

    /*
     * Listing of level
     */
    function index()
    {
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        $data['level'] = $this->Level_model->get_all_level();
        
        $this->load->view('templates/header',$data);
        $this->load->view('level/index', $data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new level
     */
    function add()
    {   
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_level' => $this->input->post('nama_level'),
            );
            
            $level_id = $this->Level_model->add_level($params);
            redirect('level/index');
        }
        else
        {            
            $this->load->view('templates/header',$data);
            $this->load->view('level/add');
            $this->load->view('templates/footer');
        }
    }  

    /*
     * Editing a level
     */
    function edit($id_level)
    {   
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);
        // check if the level exists before trying to edit it
        $data['level'] = $this->Level_model->get_level($id_level);
        
        if(isset($data['level']['id_level']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_level' => $this->input->post('nama_level'),
                );

                $this->Level_model->update_level($id_level,$params);            
                redirect('level/index');
            }
            else
                {
                $this->load->view('templates/header',$data);
                $this->load->view('level/edit', $data);
                $this->load->view('templates/footer');
            }
        }
        else
            show_error('The level you are trying to edit does not exist.');
    } 

    /*
     * Deleting level
     */
    function remove($id_level)
    {
        $level = $this->Level_model->get_level($id_level);

        // check if the level exists before trying to delete it
        if(isset($level['id_level']))
        {
            $this->Level_model->delete_level($id_level);
            redirect('level/index');
        }
        else
            show_error('The level you are trying to delete does not exist.');
    }
    
}
