<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class pengguna extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('form');
        $this->load->library('form_validation');
        $this->load->model('pengguna_model');
        $this->load->model('user_model');
        $this->load->model('jurusan_model');
        $this->load->model('level_model');
        $this->load->model('prodi_model');
    } 

    /*
     * Listing of pengguna
     */
    function index()
    {
        if(!$this->session->userdata('logged_in')) 
            redirect('home');

        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        $data['pengguna'] = $this->pengguna_model->get_all_pengguna();
        
        $this->load->view('templates/header', $data);
        $this->load->view('pengguna/index', $data);
        $this->load->view('templates/footer');
    }

    function registrasi()
    {
        if(!$this->session->userdata('logged_in')) 
            redirect('home');

        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        $data['pengguna'] = $this->pengguna_model->get_pengguna_regis();
        
        $this->load->view('templates/header', $data);
        $this->load->view('pengguna/registrasi', $data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new pengguna
     */
    function add()
    {   
        if(!$this->session->userdata('logged_in')) 
            redirect('home');

    //     if(isset($_POST) && count($_POST) > 0)     
    //     {   
    //         $params = array(
				// 'password' => $this->input->post('password'),
				// 'fk_level_id' => $this->input->post('fk_level_id'),
				// 'username' => $this->input->post('username'),
				// 'nim' => $this->input->post('nim'),
				// 'nama_lengkap' => $this->input->post('nama_lengkap'),
				// 'fk_id_jurusan' => $this->input->post('fk_id_jurusan'),
				// 'fk_id_prodi' => $this->input->post('fk_id_prodi'),
				// 'semester' => $this->input->post('semester'),
				// 'kelas' => $this->input->post('kelas'),
				// 'telpon' => $this->input->post('telpon'),
    //         );
            
    //         $pengguna_id = $this->pengguna_model->add_pengguna($params);
    //         redirect('pengguna/index');
    //     }
    //     else
    //     {            
    //             $this->load->view('templates/header');
    //             $this->load->view('pengguna/add');
    //             $this->load->view('templates/footer');
    //     }

        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        $data['level'] = $this->level_model->generate_level_dropdown();
        $data['jurusan'] = $this->jurusan_model->generate_jurusan_dropdown();
        $data['prodi'] = $this->prodi_model->generate_prodi_dropdown();
        // Kita validasi input sederhana, sila cek http://localhost/ci3/user_guide/libraries/form_validation.html
        $this->form_validation->set_rules('username', 'username', 'required|is_unique[pengguna.username]',
            array(
                'required'      => 'Isi %s terlebih dahulju.',
                'is_unique'     => 'Tipe <strong>' .$this->input->post('username'). '</strong> sudah ada.'
            ));
        // Cek apakah input valid atau tidak
        if ($this->form_validation->run() === FALSE)
        {
            $this->load->view('templates/header', $data);
            $this->load->view('pengguna/add', $data);
            $this->load->view('templates/footer');
        } else {
            // Apakah user upload gambar?
            if ( isset($_FILES['thumbnail']) && $_FILES['thumbnail']['size'] > 0 )
            {
                // Konfigurasi folder upload & file yang diijinkan
                // Jangan lupa buat folder uploads di dalam ci3-course
                $config['upload_path']          = './assets/img/pengguna/';
                $config['allowed_types']        = 'gif|jpg|png';
                $config['max_size']             = 2048;
                // Load library upload
                $this->load->library('upload', $config);
                // Apakah file berhasil diupload?
                if ( !$this->upload->do_upload('thumbnail'))
                {
                    $data['upload_error'] = $this->upload->display_errors();
                    $post_image = '';
                    // Kita passing pesan error upload ke view supaya user mencoba upload ulang
                    $this->load->view('templates/header', $data);
                    $this->load->view('pengguna/add', $data);
                    $this->load->view('templates/footer'); 
                } else {
                    // Simpan nama file-nya jika berhasil diupload
                    $img_data = $this->upload->data();
                    $post_image = $img_data['file_name'];
                    
                }
            } else {
                // User tidak upload gambar, jadi kita kosongkan field ini
                $post_image = 'default.jpg';
            }
            // Memformat slug sebagai alamat URL, 
            // Misal judul: "Hello World", kita format menjadi "hello-world"
            // Nantinya, URL blog kita menjadi mudah dibaca 
            // http://localhost/ci3-course/blog/hello-world
            // $slug = url_title($this->input->post('tipe'), 'dash', TRUE);
            $enc_password = md5($this->input->post('password'));
            $post_data = array(
                'fk_level_id' => $this->input->post('fk_level_id'),
                'username' => $this->input->post('username'),
                'password' => $enc_password,
                'nim' => $this->input->post('nim'),
                'nama_lengkap' => $this->input->post('nama_lengkap'),
                'fk_id_jurusan' => $this->input->post('fk_id_jurusan'),
                'fk_id_prodi' => $this->input->post('fk_id_prodi'),
                'tahun_masuk' => $this->input->post('tahun_masuk'),
                'telpon' => $this->input->post('telepon'),
                'foto' => $post_image,
                'status' => $this->input->post('status'),
            );
            // Jika tidak ada error upload gambar, maka kita insert ke database via model Blog 
            if( empty($data['upload_error']) ) {
                $this->pengguna_model->add_pengguna($post_data);
                redirect('pengguna'); 
            }
        }
    }  

    /*
     * Editing a pengguna
     */
    function edit($id = null)
    {   
        if(!$this->session->userdata('logged_in')) 
            redirect('home');
        // check if the pengguna exists before trying to edit it
     //    $data['pengguna'] = $this->pengguna_model->get_pengguna_by_id($id_user);
        
     //    if(isset($data['pengguna']['id_user']))
     //    {
     //        if(isset($_POST) && count($_POST) > 0)     
     //        {   
     //            $params = array(
					// 'password' => $this->input->post('password'),
					// 'fk_level_id' => $this->input->post('fk_level_id'),
					// 'username' => $this->input->post('username'),
					// 'nim' => $this->input->post('nim'),
					// 'nama_lengkap' => $this->input->post('nama_lengkap'),
					// 'fk_id_jurusan' => $this->input->post('fk_id_jurusan'),
					// 'fk_id_prodi' => $this->input->post('fk_id_prodi'),
					// 'semester' => $this->input->post('semester'),
					// 'kelas' => $this->input->post('kelas'),
					// 'telpon' => $this->input->post('telpon'),
     //            );

     //            $this->pengguna_model->update_pengguna($id_user,$params);            
     //            redirect('pengguna/index');
     //        }
     //        else
     //        {
     //            $data['_view'] = 'pengguna/edit';
     //            $this->load->view('layouts/main',$data);
     //        }
     //    }
     //    else
     //        show_error('The pengguna you are trying to edit does not exist.');

        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);
        
        $data['pengguna'] = $this->pengguna_model->get_pengguna_by_id($id);
        // Jika id kosong atau tidak ada id yg dimaksud, lempar user ke halaman blog
        if ( empty($id) || !$data['pengguna'] ) redirect('pengguna');
        // Gunakan fungsi dari model untuk mengisi data dalam dropdown
        $data['level'] = $this->level_model->generate_level_dropdown();
        $data['jurusan'] = $this->jurusan_model->generate_jurusan_dropdown();
        $data['prodi'] = $this->prodi_model->generate_prodi_dropdown();
        // Kita simpan dulu nama file yang lama
        $old_image = $data['pengguna']->foto;
        // Kita validasi input sederhana, sila cek http://localhost/ci3/user_guide/libraries/form_validation.html
        $this->form_validation->set_rules('password', 'password', 'required',
            array(
                'required'      => 'Isi %s terlebih dahulu.'
            ));
        // Cek apakah input valid atau tidak
        if ($this->form_validation->run() === FALSE)
        {
            $this->load->view('templates/header', $data);
            $this->load->view('pengguna/edit', $data);
            $this->load->view('templates/footer');
        } else {
            // Apakah user upload gambar?
            if ( isset($_FILES['thumbnail']) && $_FILES['thumbnail']['size'] > 0 )
            {
                // Konfigurasi folder upload & file yang diijinkan
                // Jangan lupa buat folder uploads di dalam ci3-course
                $config['upload_path']          = './assets/img/pengguna/';
                $config['allowed_types']        = 'gif|jpg|png';
                $config['max_size']             = 2048;
                $config['max_width']            = 1000;
                $config['max_height']           = 2000;
                // Load library upload
                $this->load->library('upload', $config);
                // Apakah file berhasil diupload?
                if ( ! $this->upload->do_upload('thumbnail'))
                {
                    $data['upload_error'] = $this->upload->display_errors();
                    $post_image = '';
                    // Kita passing pesan error upload ke view supaya user mencoba upload ulang
                    $this->load->view('templates/header', $data);
                    $this->load->view('pengguna/edit', $data);
                    $this->load->view('templates/footer');
                } else {
                    // Hapus file image yang lama jika ada
                    if( !empty($old_image) ) {
                        if ( file_exists( './assets/img/pengguna/'.$old_image ) ){
                            unlink( './assets/img/pengguna/'.$old_image );
                        } else {
                            echo 'File tidak ditemukan.';
                        }
                    }
                    // Simpan nama file-nya jika berhasil diupload
                    $img_data = $this->upload->data();
                    $post_image = $img_data['file_name'];
                    
                }
            } else {
                // User tidak upload gambar, jadi kita kosongkan field ini, atau jika sudah ada, gunakan image sebelumnya
                $post_image = ( !empty($old_image) ) ? $old_image : '';
            }
            $enc_password = md5($this->input->post('password'));
            $post_data = array(
                'username' => $this->input->post('username'),
                'password' => $enc_password,
                'nim' => $this->input->post('nim'),
                'nama_lengkap' => $this->input->post('nama_lengkap'),
                'fk_id_jurusan' => $this->input->post('fk_id_jurusan'),
                'fk_id_prodi' => $this->input->post('fk_id_prodi'),
                'tahun_masuk' => $this->input->post('tahun_masuk'),
                'telpon' => $this->input->post('telepon'),
                'foto' => $post_image,
                'status' => $this->input->post('status'),
            );
            // Jika tidak ada error upload gambar, maka kita update datanya 
            if( empty($data['upload_error']) ) {
                // Update artikel sesuai post_data dan id-nya
                $this->pengguna_model->update_pengguna($post_data, $id);
                redirect('pengguna');
            }
        }
    } 

    /*
     * Deleting pengguna
     */
    function remove($id)
    {
        $data['pengguna'] = $this->pengguna_model->get_pengguna_by_id($id);

        // // check if the pengguna exists before trying to delete it
        // if(isset($pengguna['id_user']))
        // {
        //     $this->pengguna_model->delete_pengguna($id);
        //     redirect('pengguna/index');
        // }
        // else
        //     show_error('The pengguna you are trying to delete does not exist.');

        if ( empty($id) || !$data['pengguna'] ) show_404();
        // Kita simpan dulu nama file yang lama
        $old_image = $data['pengguna']->foto;
        // Hapus file image yang lama jika ada
        if( !empty($old_image) ) {
            if ( file_exists( './assets/img/pengguna/'.$old_image )){
                unlink( './assets/img/pengguna/'.$old_image);
            } else {
                echo 'File tidak ditemukan.';
            }
        }
        // Hapus artikel sesuai id-nya
        if( ! $this->pengguna_model->delete_pengguna($id) )
        {
            // Jika gagal, tampilkan failnya
            echo "gagal menghapus";
        } else {
            // Ok, sudah terhapus
            redirect('pengguna');
        }
    }
    
}
