<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Point extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Point_model');
        $this->load->model('user_model');
        $this->load->model('pengguna_model');
        $this->load->model('notifikasi_model');
        $this->load->model('notifikasi_model');
    } 

    /*
     * Listing of point
     */
    function index()
    {
            redirect('pengguna/mahasiswa');
    }

    function lihat($id_user)
    {   
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);

        $data['pengguna'] = $this->pengguna_model->get_pengguna_by_id($id_user);
        $data['point'] = $this->Point_model->get_all_point_by_id($id_user);

        $data['total_point'] = $this->Point_model->get_total_point($id_user);
        $data['total_point_him'] = $this->Point_model->get_total_point_him($id_user);
        $data['total_point_bem'] = $this->Point_model->get_total_point_bem($id_user);
        $data['total_point_dpk'] = $this->Point_model->get_total_point_dpk($id_user);

        $data['total_point_mah'] = $this->Point_model->jumlahpoin($id_user);
        $data['total_point_mah_drhim'] = $this->Point_model->jumlahpoinhim($id_user);
        $data['total_point_mah_drbem'] = $this->Point_model->jumlahpoinbem($id_user);
        $data['total_point_mah_drdpk'] = $this->Point_model->jumlahpoindpk($id_user);
        
        $this->load->view('templates/header',$data);
        $this->load->view('point/index', $data);
        $this->load->view('templates/footer');
    }

    function krm_bem($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $user_id=$id;

        $post_data = array('verif_him_sdh'=>1 ,'verif_bem'=>1,
            );
        $data_notif = array(
            'judul_notifikasi' => 'Semua point anda telah dikirim ke BEM',
            'fk_id_user' => $user_id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->pengguna_model->update_pengguna($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('pengguna');
    } 
    function btl_krm_bem($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $post_data = array('verif_him_sdh'=>0 ,'verif_bem'=>0,'verif_bem_sdh'=>0 ,'verif_dpk'=>0,'verif_all'=>0
            );
            // Update kategori sesuai post_data dan id-nya
            $this->pengguna_model->update_pengguna($post_data, $id);
                redirect('pengguna');
    } 
    function krm_dpk($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        $user_id=$id;

        $post_data = array('verif_bem_sdh'=>1 ,'verif_dpk'=>1,
            );
        $data_notif = array(
            'judul_notifikasi' => 'Semua point anda telah dikirim ke DPK',
            'fk_id_user' => $user_id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->pengguna_model->update_pengguna($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('pengguna/mahasiswa');
    }
    function btl_krm_dpk($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $post_data = array('verif_bem_sdh'=>0 ,'verif_dpk'=>0,'verif_all'=>0
            );
            // Update kategori sesuai post_data dan id-nya
            $this->pengguna_model->update_pengguna($post_data, $id);
                redirect('pengguna/mahasiswa');
    } 

    function dpk_setuju($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        $user_id=$id;

        $post_data = array('verif_all'=>1,
            );
        $data_notif = array(
            'judul_notifikasi' => 'Disetujui DPK untuk semua poin',
            'fk_id_user' => $user_id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->pengguna_model->update_pengguna($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('pengguna');
    } 
    function btl_dpk_setuju($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        $user_id=$id;

        $post_data = array('verif_all'=>0,
            );
        $data_notif = array(
            'judul_notifikasi' => 'DPK membatalkan persetujuan semua poin anda',
            'fk_id_user' => $user_id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->pengguna_model->update_pengguna($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('pengguna');
    } 

    function verif_himp($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $user = $this->Point_model->get_point($id);
        $user_id=$user['fk_id_user'];

        $post_data = array('verif_himp' => 1,
            );

        $data_notif = array(
            'judul_notifikasi' => 'Poin di-Verifikasi Himpunan',
            'fk_id_user' => $user_id,
            );

            // Update kategori sesuai post_data dan id-nya
            $this->Point_model->update_point($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('point/lihat/'.$user_id);
    }
    function no_verif_himp($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        
        $user = $this->Point_model->get_point($id);
        $user_id=$user['fk_id_user'];

        $post_data = array('verif_himp' => 0,
            );
        $data_notif = array(
            'judul_notifikasi' => 'Verifikasi poin dibatalkan',
            'fk_id_user' => $user_id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->Point_model->update_point($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('point/lihat/'.$user_id);
    }

    function verif_bem($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $user = $this->Point_model->get_point($id);
        $user_id=$user['fk_id_user'];

        $post_data = array('verif_bemm' => 1,
            );
        $data_notif = array(
            'judul_notifikasi' => 'Poin di-Verifikasi BEM',
            'fk_id_user' => $user_id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->Point_model->update_point($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('point/lihat/'.$user_id);
    }
    function no_verif_bem($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        
        $user = $this->Point_model->get_point($id);
        $user_id=$user['fk_id_user'];

        $post_data = array('verif_bemm' => 0,
            );
        $data_notif = array(
            'judul_notifikasi' => 'Verifikasi poin dibatalkan',
            'fk_id_user' => $user_id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->Point_model->update_point($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('point/lihat/'.$user_id);
    }

    function verif_dpk($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $user = $this->Point_model->get_point($id);
        $user_id=$user['fk_id_user'];

        $post_data = array('verif_dpka' => 1,
            );
        $data_notif = array(
            'judul_notifikasi' => 'Poin di-Verifikasi DPK',
            'fk_id_user' => $user_id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->Point_model->update_point($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('point/lihat/'.$user_id);
    }
    function no_verif_dpk($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        
        $user = $this->Point_model->get_point($id);
        $user_id=$user['fk_id_user'];

        $post_data = array('verif_dpka' => 0,
            );
        $data_notif = array(
            'judul_notifikasi' => 'Verifikasi poin dibatalkan',
            'fk_id_user' => $user_id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->Point_model->update_point($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('point/lihat/'.$user_id);
    }


    function verif_all($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $idList = $_GET['id_list'];

        //print_r($id);
        
        // $user = $this->Point_model->get_point($id);
        // $user_id=$user['fk_id_user'];

        $post_data = array('verif_all' => 1,
            );

        foreach($idList as $idTunggal)
            // Update kategori sesuai post_data dan id-nya
            $this->pengguna_model->update_pengguna($post_data, $idTunggal);
                redirect('pengguna');

    }

    function verif_all_satu_mah($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');
        

        $post_data = array('verif_dpk' => 1,'verif_all' => 1,
            );
        $data_notif = array(
            'judul_notifikasi' => 'Semua point di-Verifikasi DPK',
            'fk_id_user' => $id,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->Point_model->update_all_point_mah($post_data, $id);
            $this->notifikasi_model->add_notifikasi($data_notif);
                redirect('point/update_point/'.$id);
    }
    function update_point($id){
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $post_data = array('verif_dpka' => 1,
            );
            // Update kategori sesuai post_data dan id-nya
            $this->Point_model->update_all_point_mah_b($post_data, $id);
                redirect('pengguna');
    }


    /*
     * Editing a point
     */
    function edit($id_point)
    {   
        // check if the point exists before trying to edit it
        $data['point'] = $this->Point_model->get_point($id_point);
        
        if(isset($data['point']['id_point']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_id_user' => $this->input->post('fk_id_user'),
					'nama_sertifikat' => $this->input->post('nama_sertifikat'),
					'foto_sertifikat' => $this->input->post('foto_sertifikat'),
					'fk_id_kategori' => $this->input->post('fk_id_kategori'),
					'angka_kredit' => $this->input->post('angka_kredit'),
                );

                $this->Point_model->update_point($id_point,$params);            
                redirect('point/index');
            }
            else
            {
                $data['_view'] = 'point/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The point you are trying to edit does not exist.');
    } 

    /*
     * Deleting point
     */
    function remove($id)
    {
        // $point = $this->Point_model->get_point($id_point);

        // // check if the point exists before trying to delete it
        // if(isset($point['id_point']))
        // {
        //     $this->Point_model->delete_point($id_point);
        //     redirect('point/index');
        // }
        // else
        //     show_error('The point you are trying to delete does not exist.');

        $data = $this->Point_model->get_point($id);
        $user_id=$data['fk_id_user'];
        if ( empty($id) ) show_404();
        // Kita simpan dulu nama file yang lama
        $old_image = $data['foto_sertifikat'];
        // Hapus file image yang lama jika ada
        if( !empty($old_image) ) {
            if ( file_exists( './assets/img/point/'.$old_image )){
                unlink( './assets/img/point/'.$old_image);
            } else {
                echo 'File tidak ditemukan.';
            }
        }
        // Hapus artikel sesuai id-nya
        if( ! $this->Point_model->delete_point($id) )
        {
            // Jika gagal, tampilkan failnya
            echo "gagal menghapus";
        } else {
            // Ok, sudah terhapus
            redirect('point/lihat/'.$user_id);
        }
    }
    
}
