<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Point extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Point_model');
        $this->load->model('user_model');
    } 

    /*
     * Listing of point
     */
    function index()
    {
        if(!$this->session->userdata('logged_in')) 
            redirect('home/indexx');

        $user_id = $this->session->userdata('id_user');
        // Dapatkan detail user
        $data['user'] = $this->user_model->get_user_details($user_id);
        
        $data['point'] = $this->Point_model->get_all_point();

        
        $this->load->view('templates/header',$data);
        $this->load->view('point/index', $data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new point
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_id_user' => $this->input->post('fk_id_user'),
				'nama_sertifikat' => $this->input->post('nama_sertifikat'),
				'foto_sertifikat' => $this->input->post('foto_sertifikat'),
				'fk_id_kategori' => $this->input->post('fk_id_kategori'),
				'angka_kredit' => $this->input->post('angka_kredit'),
            );
            
            $point_id = $this->Point_model->add_point($params);
            redirect('point/index');
        }
        else
        {            
            $this->load->view('themes/header');
            $this->load->view('pengguna/add');
            $this->load->view('themes/footer');
        }
    }  

    /*
     * Editing a point
     */
    function edit($id_point)
    {   
        // check if the point exists before trying to edit it
        $data['point'] = $this->Point_model->get_point($id_point);
        
        if(isset($data['point']['id_point']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_id_user' => $this->input->post('fk_id_user'),
					'nama_sertifikat' => $this->input->post('nama_sertifikat'),
					'foto_sertifikat' => $this->input->post('foto_sertifikat'),
					'fk_id_kategori' => $this->input->post('fk_id_kategori'),
					'angka_kredit' => $this->input->post('angka_kredit'),
                );

                $this->Point_model->update_point($id_point,$params);            
                redirect('point/index');
            }
            else
            {
                $data['_view'] = 'point/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The point you are trying to edit does not exist.');
    } 

    /*
     * Deleting point
     */
    function remove($id_point)
    {
        $point = $this->Point_model->get_point($id_point);

        // check if the point exists before trying to delete it
        if(isset($point['id_point']))
        {
            $this->Point_model->delete_point($id_point);
            redirect('point/index');
        }
        else
            show_error('The point you are trying to delete does not exist.');
    }
    
}
