<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kategori_induk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kategori by id_kategori_point
     */
    function get_kategori_induk($id)
    {
        return $this->db->get_where('kategori_induk',array('kode_kategori_induk'=>$id))->row_array();
    }
        
    /*
     * Get all kategori
     */
    function get_all_kategori_induk()
    {
        return $this->db->get('kategori_induk')->result_array();
        // $hasil=$this->db->query("SELECT * FROM kategori_induk");
        // return $hasil;
    }
    function get_all_kategori_induk_wajib()
    {
        // return $this->db->get_where('kategori_induk',array('wajib'=>1))->result_array();
        $hasil=$this->db->query("SELECT * FROM kategori_induk where wajib=1");
        return $hasil;
    }
    function get_all_kategori_induk_tidak_wajib()
    {
        // return $this->db->get_where('kategori_induk',array('wajib'=>0))->result_array();
        $hasil=$this->db->query("SELECT * FROM kategori_induk where wajib=0");
        return $hasil;
    }

    function ambil_kategori($id){
        $hasil=$this->db->query("SELECT * FROM kategori WHERE fk_kode_kategori_induk='$id'");
        return $hasil->result();
    }
        
    /*
     * function to add new kategori
     */
    function add_kategori_induk($params)
    {
        $this->db->insert('kategori_induk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kategori
     */
    function update_kategori_induk($kode,$params)
    {
        $this->db->where('kode_kategori_induk',$kode);
        return $this->db->update('kategori_induk',$params);
    }
    
    /*
     * function to delete kategori
     */
    function delete_kategori_induk($id)
    {
        return $this->db->delete('kategori_induk',array('kode_kategori_induk'=>$id));
    }


    public function generate_kategori_induk_dropdown() {

            // Mendapatkan data ID dan nama kategori saja
            $this->db->select ('
                kategori_induk.kode_kategori_induk,
                kategori_induk.jenis_kegiatan
            ');
            // Urut abjad
            $this->db->order_by('kode_kategori_induk');
            $result = $this->db->get('kategori_induk');
            
            // bikin array
            // please select berikut ini merupakan tambahan saja agar saat pertama
            // diload akan ditampilkan text please select.
            $dropdown[''] = 'Pilih';
            if ($result->num_rows() > 0) {
                
                foreach ($result->result_array() as $row) {
                    // Buat array berisi 'value' (id kategori) dan 'nama' (nama kategori)
                    $dropdown[$row['kode_kategori_induk']] = $row['jenis_kegiatan'];
                }
            }
            return $dropdown;
        }
}
