<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kegiatan_pengguna_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kegiatan_pengguna by id_daftar_keg
     */
    function get_kegiatan_pengguna($id)
    {
        return $this->db->get_where('kegiatan_pengguna',array('id_keg_pengguna'=>$id))->row_array();
    }
        
    /*
     * Get all kegiatan_pengguna
     */
    function get_all_kegiatan_pengguna()
    {
        $this->db->join('pengguna', 'pengguna.id_user = kegiatan_pengguna.fk_id_user');
        $this->db->join('kegiatan', 'kegiatan.id_kegiatan = kegiatan_pengguna.fk_id_keg');
        $this->db->join('jurusan', 'jurusan.id_jurusan = pengguna.fk_id_jurusan');
        $this->db->join('prodi', 'prodi.id_prodi = pengguna.fk_id_prodi');

        $this->db->order_by('id_keg_pengguna', 'desc');
        return $this->db->get('kegiatan_pengguna')->result_array();
    }
        
    /*
     * function to add new kegiatan_pengguna
     */
    function add_kegiatan_pengguna($params)
    {
        $this->db->insert('kegiatan_pengguna',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kegiatan_pengguna
     */
    function update_keg_pengguna($data,$id)
    {
        $this->db->where('id_keg_pengguna',$id);
        return $this->db->update('kegiatan_pengguna',$data);
    }
    
    /*
     * function to delete kegiatan_pengguna
     */
    function delete_kegiatan_pengguna($id_daftar_keg)
    {
        return $this->db->delete('kegiatan_pengguna',array('id_daftar_keg'=>$id_daftar_keg));
    }
}
