<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kegiatan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    public function get_kegiatan_by_id($id)
        {
             // Inner Join dengan table brand
            $this->db->join('kategori', 'kategori.id_kategori_point = kegiatan.fk_kategori_kegiatan');
            $this->db->join('pengguna', 'pengguna.id_user = kegiatan.dibuat');
            $this->db->join('level', 'level.id_level = kegiatan.dibuat');

            $query = $this->db->get_where('kegiatan', array('id_kegiatan' => $id));
                        
            return $query->row();
        }

    public function get_total(){
            // Dapatkan jumlah total artikel
            return $this->db->count_all("kegiatan");
        }
        
    /*
     * Get all kegiatan
     */
    function get_all_kegiatan()
    {
        // $this->db->order_by('id_kegiatan', 'desc');
        // return $this->db->get('kegiatan')->result_array();

            $this->db->order_by('kegiatan.id_kegiatan', 'DESC');

            // Inner Join dengan table kategori
            $this->db->join('kategori', 'kategori.id_kategori_point = kegiatan.fk_kategori_kegiatan');
            $this->db->join('pengguna', 'pengguna.id_user = kegiatan.dibuat');
            $this->db->join('level', 'level.id_level = kegiatan.dibuat');
            
            $query = $this->db->get('kegiatan');

            // Return dalam bentuk object
            return $query->result();
    }
        
    /*
     * function to add new kegiatan
     */
    function add_kegiatan($data)
    {
        // $this->db->insert('kegiatan',$params);
        // return $this->db->insert_id();
        return $this->db->insert('kegiatan', $data);
    }
    
    /*
     * function to update kegiatan
     */
    function update_kegiatan($data,$id)
    {
        // $this->db->where('id_kegiatan',$id_kegiatan);
        // return $this->db->update('kegiatan',$params);
        if ( !empty($data) && !empty($id) ){
                $update = $this->db->update( 'kegiatan', $data, array('id_kegiatan'=>$id) );
                return $update ? true : false;
            } else {
                return false;
            }
    }
    
    /*
     * function to delete kegiatan
     */
    function delete_kegiatan($id_kegiatan)
    {
        // return $this->db->delete('kegiatan',array('id_kegiatan'=>$id_kegiatan));
        if ( !empty($id_kegiatan) ){
                $delete = $this->db->delete('kegiatan', array('id_kegiatan'=>$id_kegiatan) );
                return $delete ? true : false;
            } else {
                return false;
            }
    }
}
