<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Level_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get level by id_level
     */
    function get_level($id_level)
    {
        return $this->db->get_where('level',array('id_level'=>$id_level))->row_array();
    }
        
    /*
     * Get all level
     */
    function get_all_level()
    {
        $this->db->order_by('id_level', 'desc');
        return $this->db->get('level')->result_array();
    }
        
    /*
     * function to add new level
     */
    function add_level($params)
    {
        $this->db->insert('level',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update level
     */
    function update_level($id_level,$params)
    {
        $this->db->where('id_level',$id_level);
        return $this->db->update('level',$params);
    }
    
    /*
     * function to delete level
     */
    function delete_level($id_level)
    {
        return $this->db->delete('level',array('id_level'=>$id_level));
    }

    public function generate_level_dropdown() {
            // Mendapatkan data ID dan nama kategori saja
            $this->db->select ('
                level.id_level,
                level.nama_level
            ');
            // Urut abjad
            $this->db->order_by('nama_level');
            $result = $this->db->get('level');
            
            // bikin array
            // please select berikut ini merupakan tambahan saja agar saat pertama
            // diload akan ditampilkan text please select.
            $dropdown[''] = 'Pilih';
            if ($result->num_rows() > 0) {
                
                foreach ($result->result_array() as $row) {
                    // Buat array berisi 'value' (id kategori) dan 'nama' (nama kategori)
                    $dropdown[$row['id_level']] = $row['nama_level'];
                }
            }
            return $dropdown;
        }
}
