<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Notifikasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    public function get_all_notifikasi_by_pengguna_limit($id)
        {
            $this->db->order_by('dibaca', 'asc');
            $this->db->limit(5);
            return $this->db->get_where('notifikasi', array('fk_id_user' => $id))->result_array();
        }
    public function get_all_notifikasi_by_pengguna($id)
        {
            $this->db->order_by('id_notifikasi', 'desc');
            return $this->db->get_where('notifikasi', array('fk_id_user' => $id))->result_array();
        }

    public function jumlah_notifikasi($id){
       $query = $this->db->get_where('notifikasi', array('dibaca' => 0, 'fk_id_user'=>$id));
            if($query->num_rows()>0)
            {
              return $query->num_rows();
            }
            else
            {
              return 0;
            }
    }

    function add_notifikasi($data)
    {
        return $this->db->insert('notifikasi', $data);
    }

    function update_notifikasi($data,$id)
    {
        // $this->db->where('id_user',$id_user);
        // return $this->db->update('pengguna',$params);
        if ( !empty($data) && !empty($id) ){
            $update = $this->db->update( 'notifikasi', $data, array('id_notifikasi'=>$id) );
            return $update ? true : false;
        } else {
            return false;
        }
    }
    
}
