<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Point_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get point by id_point
     */
    function get_point($id_point)
    {
        return $this->db->get_where('point',array('id_point'=>$id_point))->row_array();
    }
        
    /*
     * Get all point
     */
    function get_all_point()
    {
        $this->db->order_by('id_point', 'desc');
        return $this->db->get('point')->result_array();
    }
        
    /*
     * function to add new point
     */
    function add_point($params)
    {
        $this->db->insert('point',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update point
     */
    function update_point($id_point,$params)
    {
        $this->db->where('id_point',$id_point);
        return $this->db->update('point',$params);
    }
    
    /*
     * function to delete point
     */
    function delete_point($id_point)
    {
        return $this->db->delete('point',array('id_point'=>$id_point));
    }
}
