<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Prodi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get prodi by id_prodi
     */
    function get_prodi($id_prodi)
    {
        // return $this->db->get_where('prodi',array('id_prodi'=>$id_prodi))->row_array();

        $this->db->select ( '
                prodi.*, 
                jurusan.id_jurusan as id_jurusan, 
                jurusan.nama_jurusan
            ' );
            $this->db->join('jurusan', 'jurusan.id_jurusan = prodi.fk_id_jurusan');

            $query = $this->db->get_where('prodi', array('prodi.id_prodi' => $id_prodi));
                        
            return $query->row();
    }
        
    /*
     * Get all prodi
     */
    function get_all_prodi()
    {
        $this->db->order_by('id_prodi', 'desc');
        return $this->db->get('prodi')->result_array();
    }
        
    /*
     * function to add new prodi
     */
    function add_prodi($params)
    {
        $this->db->insert('prodi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update prodi
     */
    function update_prodi($id_prodi,$params)
    {
        // $this->db->where('id_prodi',$id_prodi);
        // return $this->db->update('prodi',$params);

        if ( !empty($params) && !empty($id_prodi) ){
                $update = $this->db->update( 'prodi', $params, array('id_prodi'=>$id_prodi) );
                return $update ? true : false;
            } else {
                return false;
            }
    }
    
    /*
     * function to delete prodi
     */
    function delete_prodi($id_prodi)
    {
        return $this->db->delete('prodi',array('id_prodi'=>$id_prodi));
    }


    public function generate_prodi_dropdown()
    {

        // Mendapatkan data ID dan nama kategori saja
        $this->db->select ('
            prodi.id_prodi,
            prodi.nama_prodi
        ');

        // Urut abjad
        $this->db->order_by('nama_prodi');

        $result = $this->db->get('prodi');
        
        // bikin array
        // please select berikut ini merupakan tambahan saja agar saat pertama
        // diload akan ditampilkan text please select.
        $dropdown[''] = 'Pilih prodi';

        if ($result->num_rows() > 0) {
            
            foreach ($result->result_array() as $row) {
                $dropdown[$row['id_prodi']] = $row['nama_prodi'];
            }
        }

        return $dropdown;
    }
}
